# -*- coding: utf-8 -*-
"""SocialMe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qdp1-mRkM0Io5WHQMdQitq9ixyD84kw7
"""

!pip install firebase-admin

import firebase_admin
from firebase_admin import credentials, firestore 
from firebase_admin import db

# # Fetch the service account key JSON file contents
cred = credentials.Certificate('/content/serviceAccountKey.json')
# # Initialize the app with a service account, granting admin privileges
firebase_admin.initialize_app(cred)
# opens 'places' collection

db = firestore.client()  # this connects to our Firestore database
collection = db.collection('messageCounts')

document = collection.get()

Messages = []
for i in document:
    Messages.append(i.id)

from google.colab import drive
drive.mount('/content/drive')

Messages

messageTo=[]
messageFrom=[]
messageDistance=[]
for message in Messages:
    doc = collection.document(message)
    res = doc.get().to_dict()
    messageTo.append(res['messageTo'])
    messageFrom.append(res['messageFrom'])
    messageDistance.append(1/res['messageCount']) ## appending reciprocal of number of msgs for distance

import pandas as pd
df = pd.DataFrame(list(zip(messageTo, messageFrom,messageDistance)),columns =['Sender', 'Reciever','NumMessages'])

df

currUser='yashi'
currNodes=[]
for f in range(len(df)):
  if df['Sender'][f]==currUser:
    currNodes.append(df['Reciever'][f])
  elif df['Reciever'][f] == currUser:
    currNodes.append(df['Sender'][f])

currNodes.append(currUser)

!pip install networkx
import networkx as nx

G=nx.from_pandas_edgelist(df, 'Sender', 'Reciever', ['NumMessages'])

userSubgraph = G.subgraph(currNodes)

nx.draw_networkx(userSubgraph)
plt.show()
plt.savefig(currUser+'0subgraph.jpg')

import numpy as np
y = np.array([SentCount,RecievedCount])

plt.pie(y)
plt.show()

!pip install pyrebase4

import pyrebase

firebaseConfig = {
  "apiKey": "AIzaSyCPdnp73mXHBA4_-TsuRoy0Vr7Ij8MEMuM",
  "authDomain": "socialme-46ebc.firebaseapp.com",
  "databaseURL": "https://socialme-46ebc-default-rtdb.asia-southeast1.firebasedatabase.app",
  "projectId": "socialme-46ebc",
  "storageBucket": "socialme-46ebc.appspot.com",
  "serviceAccount":"serviceAccountKey.json"
}

firebase_storage = pyrebase.initialize_app(firebaseConfig)
storage = firebase_storage.storage()
storage.child(currUser+"0subgraph.png").put(currUser+"0subgraph.png")

import matplotlib.pyplot as plt

nx.draw_networkx(G)
plt.show()

conda activate fire36
pip install firebase_admin